# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Deploy

on:
  push:
    #branches: [ "master" ]
  pull_request:
    #branches: [ "master" ]
  workflow_dispatch:
    inputs:
      UploadAll:
        type: boolean
        description: Create dump
        required: false
        default: false
      CommitSha256:
        type: string
        description: Commit hash string
        required: false
        default: ""


jobs:
  windows-build:

    runs-on: windows-latest

    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
            ${{ runner.os }}-nuget

    

    - uses: actions/checkout@v3
      with:
        ref: ${{inputs.CommitSha256}}
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            3.0.x
            3.1.x
            5.x
            6.x
            7.x
    

    

    - name: Restore dependencies
      run: dotnet restore /ConsoleLoggerParameters:Verbosity=Quiet
    - name: .NET versions
      run: dotnet --list-sdks
    - name: MSBuild
      run: |
        msbuild Karen.sln /property:Configuration=Debug 
        msbuild Karen.sln /property:Configuration=Release /p:DebugSymbols=false /p:DebugType=None 
        msbuild Karen.sln /property:Configuration=Testing 



    - name: Compess all
      if: ${{inputs.UploadAll}}
      run: 7z.exe a -m0=lzma -mx=9 "dump.zip" "bin/.."
    - name: Upload all
      if: ${{inputs.UploadAll}} 
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Workflow_Dump_${{github.run_number}}_${{github.sha}}
        path: dump.zip
    

    - name: Write branch data
      run: echo "${{github.ref_name}}-${{github.run_number}}" > bin/Installer/ReleaseConfig.ini

    - uses: actions/upload-artifact@v2
      with:
        name: binf
        path: bin/Installer


    - name: Upload Debug Net5.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Debug_Net5.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Debug/net5.0-windows
    - name: Upload Debug Net6.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Debug_Net6.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Debug/net6.0-windows
    - name: Upload Debug Net7.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Debug_Net7.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Debug/net7.0-windows

    - name: Upload Release Net5.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Release_Net5.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Release/net5.0-windows
    - name: Upload Release Net6.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Release_Net6.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Release/net6.0-windows
    - name: Upload Release Net7.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Release_Net7.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Release/net7.0-windows

    - name: Upload Testing Net5.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Testing_Net5.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Testing/net5.0-windows
    - name: Upload Testing Net6.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Testing_Net6.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Testing/net6.0-windows
    - name: Upload Testing Net7.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Testing_Net7.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Testing/net7.0-windows
  
  upload-result:
    runs-on: ubuntu-latest
    needs: windows-build
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{inputs.CommitSha256}}

    - uses: actions/download-artifact@v3
      with:
        name: binf
        path: Binarys/



    #- name: Upload Binarys
    #  if: inputs.CommitSha256 == '' && github.event_name != 'pull_request'
    #  uses: stefanzweifel/git-auto-commit-action@v4
      #with:
        #commit_message: Deploy last build, build number - ${{github.run_number}}
       # commit_user_email: my.emailtounity@gmail.com
     #   commit_author: Deploy Workflow
       # commit_user_name: Deploy Binarys Job
    - name: 7zr download
      run: wget -O Binarys/7zr.exe https://7-zip.org/a/7zr.exe

    - name: 7z Install
      run: |
        sudo apt install p7zip-full p7zip-rar

    - name: Installer Archive Build
      run: 7z a Binarys/Installer.zip Binarys/7zr.exe Binarys/installer.exe Binarys/ReleaseConfig.ini Binarys/gui.bin 

    #- name: Release
    #  uses: softprops/action-gh-release@v1
    #  if: inputs.CommitSha256 == '' && github.event_name != 'pull_request'
    #  with:
    #    tag_name: ${{github.ref_name}}-${{github.run_number}}
    #    target_commitish: ${{github.ref_name}}
    #    token: ${{secrets.KAREN_RELEASE_TOKEN1}}
    #    repository: lesh6295-png/KarenReleases
    #    files: |
    #      Binarys/d5.bin
    #      Binarys/d6.bin
    #      Binarys/d7.bin
    #      Binarys/r5.bin
    #      Binarys/r6.bin
    #      Binarys/r7.bin
    #      Binarys/t5.bin
    #      Binarys/t6.bin
    #      Binarys/t7.bin
    #      Binarys/Installer.zip
    #  env:
    #    GITHUB_REPOSITORY: lesh6295-png/KarenReleases
    - name: TestRelease
      uses: softprops/action-gh-release@v1
      with:
        token: ${{secrets.KAREN_RELEASE_TOKEN1}}
        repository: lesh6295-png/KarenReleases
        tag_name: ${{github.ref_name}}-${{github.run_number}}
        name: ${{github.ref_name}}-${{github.run_number}}



    - name: Print test
      run: tree -fi

