# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Deploy

on:
  push:
    #branches: [ "master" ]
  pull_request:
    #branches: [ "master" ]
  workflow_dispatch:
    inputs:
      UploadAll:
        type: boolean
        description: Bool value, if true upload artifact with root Karen folder
        required: false
        default: true
      CommitSha256:
        type: string
        description: Commit hash string
        required: false
        default: ""


jobs:
  window-build:

    runs-on: windows-latest

    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
            ${{ runner.os }}-nuget

    

    - uses: actions/checkout@v3
      with:
        ref: ${{inputs.CommitSha256}}
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            3.0.x
            3.1.x
            5.x
            6.x
            7.x
    

    

    - name: Restore dependencies
      run: dotnet restore /ConsoleLoggerParameters:Verbosity=Quiet
    - name: .NET versions
      run: dotnet --list-sdks
    - name: MSBuild
      run: |
        msbuild Karen.sln /property:Configuration=Debug
        msbuild Karen.sln /property:Configuration=Release /p:DebugSymbols=false /p:DebugType=None
        msbuild Karen.sln /property:Configuration=Testing



    - name: Compess all
      if: ${{inputs.UploadAll}}
      run: 7z.exe a -m0=lzma -mx=9 "dump.zip" "bin/.."
    - name: Upload all
      if: ${{inputs.UploadAll}} 
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Workflow_Dump_${{github.run_number}}_${{github.sha}}
        path: dump.zip
    

    - name: Write branch data
      run: echo "${{github.ref}}" > bin/Installer/BranchConfig.ini

    - uses: actions/upload-artifact@v2
      with:
        name: binf
        path: bin/Installer


    - name: Upload Debug Net5.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Debug_Net5.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Debug/net5.0-windows
    - name: Upload Debug Net6.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Debug_Net6.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Debug/net6.0-windows
    - name: Upload Debug Net7.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Debug_Net7.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Debug/net7.0-windows

    - name: Upload Release Net5.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Release_Net5.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Release/net5.0-windows
    - name: Upload Release Net6.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Release_Net6.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Release/net6.0-windows
    - name: Upload Release Net7.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Release_Net7.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Release/net7.0-windows

    - name: Upload Testing Net5.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Testing_Net5.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Testing/net5.0-windows
    - name: Upload Testing Net6.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Testing_Net6.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Testing/net6.0-windows
    - name: Upload Testing Net7.0
      uses: actions/upload-artifact@v1
      with:
        name: Karen_Testing_Net7.0_${{github.run_number}}_${{github.sha}}
        path: bin/Karen/Testing/net7.0-windows
  
  upload-result:
    runs-on: ubuntu-latest
    needs: window-build
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{inputs.CommitSha256}}

    - uses: actions/download-artifact@v3
      with:
        name: binf
        path: Binarys/



    - name: Upload Binarys
      if: inputs.CommitSha256 == '' && github.event_name != 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Deploy last build, build number - ${{github.run_number}}
        commit_user_name: Deploy Binarys Job

    - name: Print test
      run: tree -fi

