name: Deploy
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: |
        msbuild Karen.sln /property:Configuration=Debug 
        msbuild Karen.sln /property:Configuration=Release /p:DebugSymbols=false /p:DebugType=None 
        msbuild Karen.sln /property:Configuration=Testing 
    - name: IO
      run: dir -s
    - name: Write Release Info
      run: echo "stable-${{github.run_number}}" > bin/Installer/ReleaseConfig.ini

    - uses: actions/upload-artifact@v2
      with:
        name: binf
        path: bin/Installer
        
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download binarys
        uses: actions/download-artifact@v3
        with:
          name: binf
          path: Binarys/
      - name: Change Directory
        run: cd Binarys/
      - name: 7z install
        run: sudo apt install p7zip-full p7zip-rar
      - name: 7zr download
        run: wget -O 7zr.exe https://7-zip.org/a/7zr.exe
      - name: IO
        run: ls -r
      - name: Pack
        run: 7z a Installer.zip 7zr.exe installer.exe ReleaseConfig.ini gui.bin
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'pull_request'
        with:
          tag_name: stable-${{github.run_number}}
          target_commitish: ${{github.ref_name}}
          files: |
            r7.bin
            Installer.zip
